# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Laboratory for Software Design
email: hridesh@iastate.edu
description: >
  TODO
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fraolbatole.github.io/demo"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - _scripts
  - _citation_styles
  - README.md


collections:
  papers:  # Declare the `papers` collection, and output a page for every item.
    output: true

defaults:
  - scope:  # Make `papers` use the the `paper` layout by default.
      type: papers
      path: ""
    values:
      layout: paper
  - scope:  # Make all `posts` use the `news` layout and namespace by default.
      type: posts
      path: ""
    values:
      layout: news
      permalink: '/news/:categories/:year/:month/:day/:title/'

static_files:
  extname: pdf

scholar:
  source: .
# Plugins
plugins:
  - jekyll-paginate
  - jekyll/scholar

whitelist:
  - jekyll-paginate
  - jekyll/scholar
